///************************************************
/// Generated by: tund
/// Date: 24/08/2011 03:03:31
/// Goal: Create Form for GD_PRODUCT_PRICE
///************************************************


using System;
using System.Data;
using System.Drawing;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;

using IP.Core.IPCommon;
using IP.Core.IPException;
using IP.Core.IPData;
using IP.Core.IPUserService;

using SaleUS;
using SaleDS;
using Sale.CDBNames;

using C1.Win.C1FlexGrid;

namespace SaleApp
{



	public class f311_product_price : System.Windows.Forms.Form
	{
		internal System.Windows.Forms.ImageList ImageList;
		internal System.Windows.Forms.Panel m_pnl_out_place_dm;
        private C1.Win.C1FlexGrid.C1FlexGrid m_fg;
        internal SIS.Controls.Button.SiSButton m_cmd_exit;
        private Label m_lbl_price_date;
        private Label m_lbl_product_name;
        private DateTimePicker m_dat_price_date;
        private ComboBox m_cbo_product_name;
        private Label mlbl_add_category;
		private System.ComponentModel.IContainer components;

		public f311_product_price()
		{
			//
			// Required for Windows Form Designer support
			//
			InitializeComponent();

			//
			// TODO: Add any constructor code after InitializeComponent call
			//
			format_controls();
		}

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		protected override void Dispose( bool disposing )
		{
			if( disposing )
			{
				if(components != null)
				{
					components.Dispose();
				}
			}
			base.Dispose( disposing );
		}

		#region Windows Form Designer generated code
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(f311_product_price));
            this.ImageList = new System.Windows.Forms.ImageList(this.components);
            this.m_pnl_out_place_dm = new System.Windows.Forms.Panel();
            this.m_cmd_exit = new SIS.Controls.Button.SiSButton();
            this.m_fg = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.m_lbl_price_date = new System.Windows.Forms.Label();
            this.m_lbl_product_name = new System.Windows.Forms.Label();
            this.m_dat_price_date = new System.Windows.Forms.DateTimePicker();
            this.m_cbo_product_name = new System.Windows.Forms.ComboBox();
            this.mlbl_add_category = new System.Windows.Forms.Label();
            this.m_pnl_out_place_dm.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.m_fg)).BeginInit();
            this.SuspendLayout();
            // 
            // ImageList
            // 
            this.ImageList.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("ImageList.ImageStream")));
            this.ImageList.TransparentColor = System.Drawing.Color.Transparent;
            this.ImageList.Images.SetKeyName(0, "");
            this.ImageList.Images.SetKeyName(1, "");
            this.ImageList.Images.SetKeyName(2, "");
            this.ImageList.Images.SetKeyName(3, "");
            this.ImageList.Images.SetKeyName(4, "");
            this.ImageList.Images.SetKeyName(5, "");
            this.ImageList.Images.SetKeyName(6, "");
            this.ImageList.Images.SetKeyName(7, "");
            this.ImageList.Images.SetKeyName(8, "");
            this.ImageList.Images.SetKeyName(9, "");
            this.ImageList.Images.SetKeyName(10, "");
            this.ImageList.Images.SetKeyName(11, "");
            this.ImageList.Images.SetKeyName(12, "");
            this.ImageList.Images.SetKeyName(13, "");
            this.ImageList.Images.SetKeyName(14, "");
            this.ImageList.Images.SetKeyName(15, "");
            this.ImageList.Images.SetKeyName(16, "");
            this.ImageList.Images.SetKeyName(17, "");
            this.ImageList.Images.SetKeyName(18, "");
            this.ImageList.Images.SetKeyName(19, "");
            this.ImageList.Images.SetKeyName(20, "");
            this.ImageList.Images.SetKeyName(21, "");
            // 
            // m_pnl_out_place_dm
            // 
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_exit);
            this.m_pnl_out_place_dm.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.m_pnl_out_place_dm.Location = new System.Drawing.Point(0, 400);
            this.m_pnl_out_place_dm.Name = "m_pnl_out_place_dm";
            this.m_pnl_out_place_dm.Padding = new System.Windows.Forms.Padding(4);
            this.m_pnl_out_place_dm.Size = new System.Drawing.Size(582, 36);
            this.m_pnl_out_place_dm.TabIndex = 19;
            // 
            // m_cmd_exit
            // 
            this.m_cmd_exit.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_exit.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_exit.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_exit.Dock = System.Windows.Forms.DockStyle.Right;
            this.m_cmd_exit.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_exit.ImageIndex = 12;
            this.m_cmd_exit.ImageList = this.ImageList;
            this.m_cmd_exit.Location = new System.Drawing.Point(490, 4);
            this.m_cmd_exit.Name = "m_cmd_exit";
            this.m_cmd_exit.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_exit.TabIndex = 11;
            this.m_cmd_exit.Text = "Thoát (Esc)";
            // 
            // m_fg
            // 
            this.m_fg.ColumnInfo = resources.GetString("m_fg.ColumnInfo");
            this.m_fg.Location = new System.Drawing.Point(36, 136);
            this.m_fg.Name = "m_fg";
            this.m_fg.Size = new System.Drawing.Size(510, 240);
            this.m_fg.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("m_fg.Styles"));
            this.m_fg.TabIndex = 20;
            // 
            // m_lbl_price_date
            // 
            this.m_lbl_price_date.AutoSize = true;
            this.m_lbl_price_date.Location = new System.Drawing.Point(73, 100);
            this.m_lbl_price_date.Name = "m_lbl_price_date";
            this.m_lbl_price_date.Size = new System.Drawing.Size(77, 13);
            this.m_lbl_price_date.TabIndex = 31;
            this.m_lbl_price_date.Text = "Ngày cập nhật";
            // 
            // m_lbl_product_name
            // 
            this.m_lbl_product_name.AutoSize = true;
            this.m_lbl_product_name.Location = new System.Drawing.Point(73, 58);
            this.m_lbl_product_name.Name = "m_lbl_product_name";
            this.m_lbl_product_name.Size = new System.Drawing.Size(74, 13);
            this.m_lbl_product_name.TabIndex = 30;
            this.m_lbl_product_name.Text = "Tên hàng hóa";
            // 
            // m_dat_price_date
            // 
            this.m_dat_price_date.CustomFormat = "dd/MM/yyyy";
            this.m_dat_price_date.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.m_dat_price_date.Location = new System.Drawing.Point(315, 93);
            this.m_dat_price_date.Name = "m_dat_price_date";
            this.m_dat_price_date.Size = new System.Drawing.Size(192, 20);
            this.m_dat_price_date.TabIndex = 29;
            // 
            // m_cbo_product_name
            // 
            this.m_cbo_product_name.FormattingEnabled = true;
            this.m_cbo_product_name.Location = new System.Drawing.Point(189, 55);
            this.m_cbo_product_name.Name = "m_cbo_product_name";
            this.m_cbo_product_name.Size = new System.Drawing.Size(318, 21);
            this.m_cbo_product_name.TabIndex = 28;
            // 
            // mlbl_add_category
            // 
            this.mlbl_add_category.AutoSize = true;
            this.mlbl_add_category.Font = new System.Drawing.Font("Arial Narrow", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.mlbl_add_category.Location = new System.Drawing.Point(168, 9);
            this.mlbl_add_category.Name = "mlbl_add_category";
            this.mlbl_add_category.Size = new System.Drawing.Size(235, 25);
            this.mlbl_add_category.TabIndex = 27;
            this.mlbl_add_category.Text = "CẬP NHẬT GIÁ SẢN PHẨM";
            // 
            // f311_product_price
            // 
            this.AutoScaleBaseSize = new System.Drawing.Size(5, 13);
            this.ClientSize = new System.Drawing.Size(582, 436);
            this.Controls.Add(this.m_lbl_price_date);
            this.Controls.Add(this.m_lbl_product_name);
            this.Controls.Add(this.m_dat_price_date);
            this.Controls.Add(this.m_cbo_product_name);
            this.Controls.Add(this.mlbl_add_category);
            this.Controls.Add(this.m_fg);
            this.Controls.Add(this.m_pnl_out_place_dm);
            this.Name = "f311_product_price";
            this.Text = "F311- Cập nhật giá bán";
            this.Load += new System.EventHandler(this.frm_GD_PRODUCT_PRICE2_Load);
            this.m_pnl_out_place_dm.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.m_fg)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

		}
		#endregion

		#region Public Interface
        public void display()
        {
            this.ShowDialog();
        }
		#endregion

		#region Data Structure
		private enum e_col_Number{
			UNIT_ID = 2,PRICE = 1
		}			
		#endregion

		#region Members
		ITransferDataRow m_obj_trans;		
		DS_GD_PRODUCT_PRICE m_ds = new DS_GD_PRODUCT_PRICE();
		US_GD_PRODUCT_PRICE m_us = new US_GD_PRODUCT_PRICE();
		#endregion

		#region Private Methods
        private void load_data_2_cbo()
        {
            US_DM_PRODUCT v_us_product = new US_DM_PRODUCT();
            DS_DM_PRODUCT v_ds_product = new DS_DM_PRODUCT();
            v_us_product.FillDataset(v_ds_product, " ORDER BY " + DM_PRODUCT.ID);
            v_ds_product.EnforceConstraints = false;
            DataRow v_dr_default = v_ds_product.DM_PRODUCT.NewDM_PRODUCTRow();


            v_dr_default[DM_PRODUCT.ID] = -1;
            v_dr_default[DM_PRODUCT.PRODUCT_NAME] = "Không có cấp trên";
            v_ds_product.DM_PRODUCT.Rows.InsertAt(v_dr_default, 0);

            m_cbo_product_name.DisplayMember = DM_PRODUCT_DE.PRODUCT_NAME;
            m_cbo_product_name.ValueMember = DM_PRODUCT_DE.ID;
            m_cbo_product_name.DataSource = v_ds_product.DM_PRODUCT;

        }
		private void format_controls(){
			CControlFormat.setFormStyle(this);
			CControlFormat.setC1FlexFormat(m_fg);
			set_define_events();
			this.KeyPreview = true;		
		}
		private void set_initial_form_load(){						
			m_obj_trans = get_trans_object(m_fg);
			load_data_2_grid();		
		}	
		private ITransferDataRow get_trans_object(C1.Win.C1FlexGrid.C1FlexGrid i_fg){
			Hashtable v_htb = new Hashtable();
			v_htb.Add(GD_PRODUCT_PRICE.UNIT_ID, e_col_Number.UNIT_ID);			v_htb.Add(GD_PRODUCT_PRICE.PRICE, e_col_Number.PRICE);									
			ITransferDataRow v_obj_trans = new CC1TransferDataRow(i_fg,v_htb,m_ds.GD_PRODUCT_PRICE.NewRow());
			return v_obj_trans;			
		}
		private void load_data_2_grid(){						
			m_ds = new DS_GD_PRODUCT_PRICE();			
			m_us.FillDataset(m_ds);
			m_fg.Redraw = false;
			CGridUtils.Dataset2C1Grid(m_ds, m_fg, m_obj_trans);
			m_fg.Redraw = true;
		}
		private void grid2us_object(US_GD_PRODUCT_PRICE i_us
			, int i_grid_row) {
			DataRow v_dr;
			v_dr = (DataRow) m_fg.Rows[i_grid_row].UserData;
			m_obj_trans.GridRow2DataRow(i_grid_row,v_dr);
			i_us.DataRow2Me(v_dr);
		}

	
		private void us_object2grid(US_GD_PRODUCT_PRICE i_us
			, int i_grid_row) {
			DataRow v_dr = (DataRow) m_fg.Rows[i_grid_row].UserData;
			i_us.Me2DataRow(v_dr);
			m_obj_trans.DataRow2GridRow(v_dr, i_grid_row);
		}


		private void insert_gd_product_price(){			
		//	frm_GD_PRODUCT_PRICE2_DE v_fDE = new  frm_GD_PRODUCT_PRICE2_DE();								
		//	v_fDE.display();
			load_data_2_grid();
		}

		private void update_gd_product_price(){			
			if (!CGridUtils.IsThere_Any_NonFixed_Row(m_fg)) return;
			if (!CGridUtils.isValid_NonFixed_RowIndex(m_fg, m_fg.Row)) return;			
			grid2us_object(m_us, m_fg.Row);
		//	frm_GD_PRODUCT_PRICE2_DE v_fDE = new frm_GD_PRODUCT_PRICE2_DE();
		//	v_fDE.display(m_us);
			load_data_2_grid();
		}
				
		private void delete_gd_product_price(){
			if (!CGridUtils.IsThere_Any_NonFixed_Row(m_fg)) return;
			if (!CGridUtils.isValid_NonFixed_RowIndex(m_fg, m_fg.Row)) return;
			if (BaseMessages.askUser_DataCouldBeDeleted(8) != BaseMessages.IsDataCouldBeDeleted.CouldBeDeleted)  return;
			US_GD_PRODUCT_PRICE v_us = new US_GD_PRODUCT_PRICE();
			grid2us_object(v_us, m_fg.Row);
			try {			
				v_us.BeginTransaction();    											
				v_us.Delete();                      								
				v_us.CommitTransaction();
				m_fg.Rows.Remove(m_fg.Row);				
			}
			catch (Exception v_e) {
				v_us.Rollback();
				CDBExceptionHandler v_objErrHandler = new CDBExceptionHandler(v_e,
					new CDBClientDBExceptionInterpret());
				v_objErrHandler.showErrorMessage();
			}
		}

		private void view_gd_product_price(){			
			if (!CGridUtils.IsThere_Any_NonFixed_Row(m_fg)) return;
			if (!CGridUtils.isValid_NonFixed_RowIndex(m_fg, m_fg.Row)) return;
			grid2us_object(m_us, m_fg.Row);
		//	frm_GD_PRODUCT_PRICE2_DE v_fDE = new frm_GD_PRODUCT_PRICE2_DE();			
		//	v_fDE.display(m_us);
		}
		private void set_define_events(){
			m_cmd_exit.Click += new EventHandler(m_cmd_exit_Click);
		
		}
		#endregion

//
		//
		//		EVENT HANLDERS
		//
		//
		private void frm_GD_PRODUCT_PRICE2_Load(object sender, System.EventArgs e) {
			try{
				set_initial_form_load();
                load_data_2_cbo();
			}
			catch (Exception v_e){
				CSystemLog_301.ExceptionHandle(v_e);
			}
		
		}

		private void m_cmd_exit_Click(object sender, EventArgs e) {
			try{
				this.Close();
			}
			catch (Exception v_e){
				CSystemLog_301.ExceptionHandle(v_e);
			}
		}

		private void m_cmd_insert_Click(object sender, EventArgs e) {
			try{
				insert_gd_product_price();
			}
			catch (Exception v_e){
				CSystemLog_301.ExceptionHandle(v_e);
			}
		}

		private void m_cmd_update_Click(object sender, EventArgs e) {
			try{
				update_gd_product_price();
			}
			catch (Exception v_e){
				CSystemLog_301.ExceptionHandle(v_e);
			}
		}

		private void m_cmd_delete_Click(object sender, EventArgs e) {
			try{
				delete_gd_product_price();
			}
			catch (Exception v_e){
				CSystemLog_301.ExceptionHandle(v_e);
			}
		}

		private void m_cmd_view_Click(object sender, EventArgs e) {
			try{
				view_gd_product_price();
			}
			catch (Exception v_e){
				CSystemLog_301.ExceptionHandle(v_e);
			}
		}

	}
}

