///************************************************
/// Generated by: linhdh
/// Date: 30/08/2011 02:33:51
/// Goal: Create User Service Class for GD_DELIVERY_ORDER
///************************************************
/// <summary>
/// Create User Service Class for GD_DELIVERY_ORDER
/// </summary>

using System;
using SaleDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;


namespace SaleUS
{
public class US_GD_DELIVERY_ORDER : US_Object
{
	private const string c_TableName = "GD_DELIVERY_ORDER";
#region Public Properties
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public string strDELIVERY_ORDER_CODE 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "DELIVERY_ORDER_CODE", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["DELIVERY_ORDER_CODE"] = value;
		}
	}

	public bool IsDELIVERY_ORDER_CODENull() 
	{
		return pm_objDR.IsNull("DELIVERY_ORDER_CODE");
	}

	public void SetDELIVERY_ORDER_CODENull() {
		pm_objDR["DELIVERY_ORDER_CODE"] = System.Convert.DBNull;
	}

	public DateTime datDELIVERY_ORDER_DATE
	{
		get   
		{
			return CNull.RowNVLDate(pm_objDR, "DELIVERY_ORDER_DATE", IPConstants.c_DefaultDate);
		}
		set   
		{
			pm_objDR["DELIVERY_ORDER_DATE"] = value;
		}
	}

	public bool IsDELIVERY_ORDER_DATENull()
	{
		return pm_objDR.IsNull("DELIVERY_ORDER_DATE");
	}

	public void SetDELIVERY_ORDER_DATENull()
	{
		pm_objDR["DELIVERY_ORDER_DATE"] = System.Convert.DBNull;
	}

	public decimal dcREPOSITORY_ID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "REPOSITORY_ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["REPOSITORY_ID"] = value;
		}
	}

	public bool IsREPOSITORY_IDNull()	{
		return pm_objDR.IsNull("REPOSITORY_ID");
	}

	public void SetREPOSITORY_IDNull() {
		pm_objDR["REPOSITORY_ID"] = System.Convert.DBNull;
	}

	public decimal dcUSER_ID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "USER_ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["USER_ID"] = value;
		}
	}

	public bool IsUSER_IDNull()	{
		return pm_objDR.IsNull("USER_ID");
	}

	public void SetUSER_IDNull() {
		pm_objDR["USER_ID"] = System.Convert.DBNull;
	}

	public decimal dcCUSTOMER_ID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "CUSTOMER_ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["CUSTOMER_ID"] = value;
		}
	}

	public bool IsCUSTOMER_IDNull()	{
		return pm_objDR.IsNull("CUSTOMER_ID");
	}

	public void SetCUSTOMER_IDNull() {
		pm_objDR["CUSTOMER_ID"] = System.Convert.DBNull;
	}

#endregion


#region Init Functions
	public US_GD_DELIVERY_ORDER() 
	{
		pm_objDS = new DS_GD_DELIVERY_ORDER();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_GD_DELIVERY_ORDER(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_GD_DELIVERY_ORDER(decimal i_dbID) 
	{
		pm_objDS = new DS_GD_DELIVERY_ORDER();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion


  }
}
